language: python
python:
  - "2.7"
  - "2.6"
  - "3.2"
#script: nosetests




#install:
#- if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors importlib unittest2; fi
#- pip install -r requirements.txt
# command to install dependencies
#script: 
    #python tests/test_all_of_the_units.py
#branches:
#    only:
#        - master

